stages:
  - build
  - distribute

variables:
  GRADLE_USER_HOME: "/.gradle"
  ANDROID_COMPILE_SDK: "35"
  ANDROID_BUILD_TOOLS: "34.0.0"
  ANDROID_SDK_ROOT: "/sdk"
  FIREBASE_CLI_LOGIN: ""

cache:
  key: ""
  paths:
    - .gradle/
    - ~/.gradle/caches/
    - ~/.gradle/wrapper/

before_script:
  - sdkmanager "platforms;android-" "build-tools;" || true
  - chmod +x ./gradlew

build_apk:
  stage: build
  image: ghcr.io/monostream/docker-android:android-34-jdk17
  script:
    - ./gradlew clean assembleRelease
  artifacts:
    paths:
      - app/build/outputs/apk/release/app-release.apk

distribute_apk:
  stage: distribute
  image: node:18
  dependencies:
    - build_apk
  before_script:
    - npm install -g firebase-tools
    - firebase login:ci --token ""
  script:
    - firebase appdistribution:distribute app/build/outputs/apk/release/app-release.apk --app "" --token ""
